// <auto-generated />
using System;
using EntLibraryProj.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntLibraryProj.Services.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20241114015739_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EntLibraryProj.Entities.Checkable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Checkable");

                    b.HasDiscriminator().HasValue("Checkable");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EntLibraryProj.Entities.LibraryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Inventory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("CheckId");

                    b.ToTable("LibraryItems");
                });

            modelBuilder.Entity("EntLibraryProj.Entities.Book", b =>
                {
                    b.HasBaseType("EntLibraryProj.Entities.Checkable");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("EntLibraryProj.Entities.Movie", b =>
                {
                    b.HasBaseType("EntLibraryProj.Entities.Checkable");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.ToTable("Checkable", t =>
                        {
                            t.Property("Created")
                                .HasColumnName("Movie_Created");

                            t.Property("Description")
                                .HasColumnName("Movie_Description");

                            t.Property("Title")
                                .HasColumnName("Movie_Title");
                        });

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("EntLibraryProj.Entities.LibraryItem", b =>
                {
                    b.HasOne("EntLibraryProj.Entities.Checkable", "Check")
                        .WithMany()
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");
                });
#pragma warning restore 612, 618
        }
    }
}
