// <auto-generated />
using System;
using EntLibraryProj.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntLibraryProj.Services.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20241130180753_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EntLibraryProj.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryInfo");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Book"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Movie"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Audiobook"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "VideoGame"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Music"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Software"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Research Paper"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Magazine"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Newspaper"
                        });
                });

            modelBuilder.Entity("EntLibraryProj.Entities.LibraryItem", b =>
                {
                    b.Property<int>("LibItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Available")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Inventory")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LibItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("LibraryItems");

                    b.HasData(
                        new
                        {
                            LibItemId = 1,
                            Available = 15,
                            CategoryId = 1,
                            CreatorName = "J.R.R. Tolkien",
                            DateAdded = "2020-06-03",
                            DateCreated = "1937-09-21",
                            Genre = "Adventure; Action; Fantasy",
                            Inventory = 15,
                            ItemDescription = "Lorum Ipsum",
                            ItemName = "The Hobbit",
                            OriginCountry = "UK",
                            Publisher = "Allen & Unwin"
                        },
                        new
                        {
                            LibItemId = 2,
                            Available = 2,
                            CategoryId = 2,
                            CreatorName = "George Lucas",
                            DateAdded = "2024-05-04",
                            DateCreated = "1999-05-15",
                            Genre = "Space Opera; Action; Epic; Fantasy; Sci-Fi",
                            Inventory = 2,
                            ItemDescription = " ",
                            ItemName = "Star Wars Episode 1: The Phantom Menace",
                            OriginCountry = "USA",
                            Publisher = "LucasFilm"
                        },
                        new
                        {
                            LibItemId = 3,
                            Available = 2,
                            CategoryId = 2,
                            CreatorName = "George Lucas",
                            DateAdded = "2024-05-04",
                            DateCreated = "2002-05-16",
                            Genre = "Space Opera; Action; Epic; Fantasy; Sci Fi",
                            Inventory = 2,
                            ItemDescription = "Memes",
                            ItemName = "Star Wars Episode 2: The Attack of the Clones",
                            OriginCountry = "USA",
                            Publisher = "LucasFilm"
                        },
                        new
                        {
                            LibItemId = 4,
                            Available = 2,
                            CategoryId = 2,
                            CreatorName = "George Lucas",
                            DateAdded = "2024-05-04",
                            DateCreated = "2005-05-15",
                            Genre = "Space Opera; Action; Epic; Fantasy; Sci-Fi",
                            Inventory = 2,
                            ItemDescription = "Hello There",
                            ItemName = "Star Wars Episode 3: The Revenge of the Sith",
                            OriginCountry = "USA",
                            Publisher = "LucasFilm"
                        },
                        new
                        {
                            LibItemId = 5,
                            Available = 1,
                            CategoryId = 2,
                            CreatorName = "Brian De Palma",
                            DateAdded = "2024-01-01",
                            DateCreated = "1983-12-01",
                            Genre = "Crime Drama; Action",
                            Inventory = 1,
                            ItemDescription = "Excellent movie. 170 Minutes runtime. ",
                            ItemName = "Scarface",
                            OriginCountry = "Italy",
                            Publisher = "Martin Bregman"
                        },
                        new
                        {
                            LibItemId = 6,
                            Available = 7,
                            CategoryId = 3,
                            CreatorName = "J.R.R. Tolkien",
                            DateAdded = "2020-12-23",
                            DateCreated = "2000-09-21",
                            Genre = "Adventure; Action; Fantasy",
                            Inventory = 7,
                            ItemDescription = "Audiobook format is xxx minutes long",
                            ItemName = "The Hobbit",
                            OriginCountry = "UK",
                            Publisher = "Allen & Unwin"
                        },
                        new
                        {
                            LibItemId = 7,
                            Available = 10,
                            CategoryId = 1,
                            CreatorName = "J.R.R. Tolkien",
                            DateAdded = "2019-07-13",
                            DateCreated = "2004-10-21",
                            Genre = "Adventure; Action; Fantasy",
                            Inventory = 10,
                            ItemDescription = "Print. 1077 pages total, this 50th anniversary edition was published in 2004. Contains 1954's The Fellowship of the Ring and The Two Towers, and 1955's The Return of the King",
                            ItemName = "The Lord of The Rings Complete Novel",
                            OriginCountry = "UK",
                            Publisher = "George Allen & Unwin"
                        },
                        new
                        {
                            LibItemId = 8,
                            Available = 3,
                            CategoryId = 4,
                            CreatorName = "Hidetaka Miyazaki/From Software",
                            DateAdded = "2024-02-26",
                            DateCreated = "2011-09-22",
                            Genre = "Adventure; Action; Dark Fantasy; Soulsborne",
                            Inventory = 3,
                            ItemDescription = "Git gud",
                            ItemName = "Dark Souls",
                            OriginCountry = "JP",
                            Publisher = "Bandai Namco"
                        },
                        new
                        {
                            LibItemId = 9,
                            Available = 3,
                            CategoryId = 4,
                            CreatorName = "Nintendo",
                            DateAdded = "2024-03-27",
                            DateCreated = "2017-10-27",
                            Genre = "Platform, Adventure; Action",
                            Inventory = 3,
                            ItemDescription = "",
                            ItemName = "Super Mario Odyssey",
                            OriginCountry = "JP",
                            Publisher = "Nintendo"
                        },
                        new
                        {
                            LibItemId = 10,
                            Available = 4,
                            CategoryId = 5,
                            CreatorName = "Pink Floyd",
                            DateAdded = "2024-04-11",
                            DateCreated = "1973-03-01",
                            Genre = "Progressive Rock",
                            Inventory = 4,
                            ItemDescription = "Pink Floyd's album The Dark Side of the Moon is certified 14x platinum in the United Kingdom, and topped the US Billboard Top LPs & Tape chart, where it has charted for 990 weeks.",
                            ItemName = "The Dark Side of the Moon",
                            OriginCountry = "UK",
                            Publisher = "Harvest Records"
                        },
                        new
                        {
                            LibItemId = 11,
                            Available = 2,
                            CategoryId = 6,
                            CreatorName = "Visual Paradigm",
                            DateAdded = "2024-05-27",
                            DateCreated = "2001-03-01",
                            Genre = "Software; UML",
                            Inventory = 2,
                            ItemDescription = "Software",
                            ItemName = "Visual Paradigm",
                            OriginCountry = "Hong Kong",
                            Publisher = "Visual Paradigm"
                        },
                        new
                        {
                            LibItemId = 12,
                            Available = 2,
                            CategoryId = 7,
                            CreatorName = "Michael W. Godfrey; Daniel M. German",
                            DateAdded = "2024-06-17",
                            DateCreated = "2008-10-04",
                            Genre = "Software Design",
                            Inventory = 2,
                            ItemDescription = "Research Paper",
                            ItemName = "The past, present, and future of software evolution",
                            OriginCountry = "Canada",
                            Publisher = "IEEE"
                        },
                        new
                        {
                            LibItemId = 13,
                            Available = 4,
                            CategoryId = 8,
                            CreatorName = "Laphams Quarterly",
                            DateAdded = "2023-11-11",
                            DateCreated = "2024-07-07",
                            Genre = "Education; Science; Philosophy",
                            Inventory = 4,
                            ItemDescription = "Learn",
                            ItemName = "Freedom",
                            OriginCountry = "USA",
                            Publisher = "Laphams Quarterly"
                        },
                        new
                        {
                            LibItemId = 14,
                            Available = 2,
                            CategoryId = 8,
                            CreatorName = "Tony Perrottet",
                            DateAdded = "2024-06-17",
                            DateCreated = "2013-06-20",
                            Genre = "History; Education",
                            Inventory = 2,
                            ItemDescription = "Are you thinking of the Roman Empire now?",
                            ItemName = "The Glory that is Rome",
                            OriginCountry = "USA",
                            Publisher = "Smithsonian Magazine"
                        },
                        new
                        {
                            LibItemId = 15,
                            Available = 1,
                            CategoryId = 9,
                            CreatorName = "The Charlotte Observer",
                            DateAdded = "2024-06-17",
                            DateCreated = "1945-08-15",
                            Genre = "History; Education",
                            Inventory = 1,
                            ItemDescription = "Newpaper from the final days of WW2. ",
                            ItemName = "PEACE! IT'S OVER",
                            OriginCountry = "USA",
                            Publisher = "The Charlotte Observer"
                        },
                        new
                        {
                            LibItemId = 16,
                            Available = 2,
                            CategoryId = 1,
                            CreatorName = "Liam Neeson",
                            DateAdded = "2020-08-02",
                            DateCreated = "1998-05-01",
                            Genre = "Action; Screenplay; Romance",
                            Inventory = 2,
                            ItemDescription = "Screenplay of the 1998 movie of the Victor Hugo Classic ",
                            ItemName = "Les Miserables",
                            OriginCountry = "USA; Germany; UK; Ireland",
                            Publisher = "Sony Pictures"
                        });
                });

            modelBuilder.Entity("EntLibraryProj.Entities.LibraryUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryCardNum")
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("itemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("itemId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntLibraryProj.Entities.LibraryItem", b =>
                {
                    b.HasOne("EntLibraryProj.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EntLibraryProj.Entities.LibraryUser", b =>
                {
                    b.HasOne("EntLibraryProj.Entities.LibraryItem", "Item")
                        .WithMany()
                        .HasForeignKey("itemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EntLibraryProj.Entities.LibraryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EntLibraryProj.Entities.LibraryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntLibraryProj.Entities.LibraryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EntLibraryProj.Entities.LibraryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
